//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Research.DynamicDataDisplay.Xbap.Samples.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Research.DynamicDataDisplay.Xbap.Samples.Strings.UIResources", typeof(UIResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Animation.
        /// </summary>
        internal static string AnimationSample {
            get {
                return ResourceManager.GetString("AnimationSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis Coloring.
        /// </summary>
        internal static string AxisColoringSample {
            get {
                return ResourceManager.GetString("AxisColoringSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample shows how to change axes&apos; colors - looks not stylish, but works :).
        /// </summary>
        internal static string AxisColoringSample_About {
            get {
                return ResourceManager.GetString("AxisColoringSample_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coastline.
        /// </summary>
        internal static string Coastline {
            get {
                return ResourceManager.GetString("Coastline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Exchange Sample.
        /// </summary>
        internal static string CurrencyExchangeSample {
            get {
                return ResourceManager.GetString("CurrencyExchangeSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden axes and graphics.
        /// </summary>
        internal static string HideAxisSample {
            get {
                return ResourceManager.GetString("HideAxisSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Histogram.
        /// </summary>
        internal static string ImageHistogram {
            get {
                return ResourceManager.GetString("ImageHistogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isolines.
        /// </summary>
        internal static string Isoline {
            get {
                return ResourceManager.GetString("Isoline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps.
        /// </summary>
        internal static string Maps {
            get {
                return ResourceManager.GetString("Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercator Shader Maps.
        /// </summary>
        internal static string MercatorShaderMaps {
            get {
                return ResourceManager.GetString("MercatorShaderMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        internal static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples to release .
        /// </summary>
        internal static string ReleaseTooltip {
            get {
                return ResourceManager.GetString("ReleaseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Simulation.
        /// </summary>
        internal static string SimulationSample {
            get {
                return ResourceManager.GetString("SimulationSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Exchange Sample.
        /// </summary>
        internal static string StockExchangeSample {
            get {
                return ResourceManager.GetString("StockExchangeSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltips on markers.
        /// </summary>
        internal static string TooltipSample {
            get {
                return ResourceManager.GetString("TooltipSample", resourceCulture);
            }
        }
    }
}
