//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Research.DynamicDataDisplay.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Research.DynamicDataDisplay.Strings.UIResources", typeof(UIResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is in «Auto Fit» mode by default. Using mouse with.
        /// </summary>
        internal static string About_1 {
            get {
                return ResourceManager.GetString("About_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse drag.
        /// </summary>
        internal static string About_10 {
            get {
                return ResourceManager.GetString("About_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — Select an area with current aspect ratio.
        /// </summary>
        internal static string About_11 {
            get {
                return ResourceManager.GetString("About_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — Select an area to zoom in.
        /// </summary>
        internal static string About_12 {
            get {
                return ResourceManager.GetString("About_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — Fit to view.
        /// </summary>
        internal static string About_13 {
            get {
                return ResourceManager.GetString("About_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — Copy screenshot of chart to clipboard.
        /// </summary>
        internal static string About_14 {
            get {
                return ResourceManager.GetString("About_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — Save screenshot of chart.
        /// </summary>
        internal static string About_15 {
            get {
                return ResourceManager.GetString("About_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string About_2 {
            get {
                return ResourceManager.GetString("About_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pressed down you can manually select an area to display..
        /// </summary>
        internal static string About_3 {
            get {
                return ResourceManager.GetString("About_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse wheel.
        /// </summary>
        internal static string About_4 {
            get {
                return ResourceManager.GetString("About_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string About_5 {
            get {
                return ResourceManager.GetString("About_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string About_6 {
            get {
                return ResourceManager.GetString("About_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keys  —  Zoom in/Zoom out.
        /// </summary>
        internal static string About_7 {
            get {
                return ResourceManager.GetString("About_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse drag.
        /// </summary>
        internal static string About_8 {
            get {
                return ResourceManager.GetString("About_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — Pan the display area.
        /// </summary>
        internal static string About_9 {
            get {
                return ResourceManager.GetString("About_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://dynamicdatadisplay.codeplex.com.
        /// </summary>
        internal static string AboutSiteUrl {
            get {
                return ResourceManager.GetString("AboutSiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About DynamicDataDisplay.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy screenshot.
        /// </summary>
        internal static string ContextMenuCopyScreenshot {
            get {
                return ResourceManager.GetString("ContextMenuCopyScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy screenshot of charts to clipboard.
        /// </summary>
        internal static string ContextMenuCopyScreenshotTooltip {
            get {
                return ResourceManager.GetString("ContextMenuCopyScreenshotTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to view.
        /// </summary>
        internal static string ContextMenuFitToView {
            get {
                return ResourceManager.GetString("ContextMenuFitToView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make visible area fit to display entire contents.
        /// </summary>
        internal static string ContextMenuFitToViewTooltip {
            get {
                return ResourceManager.GetString("ContextMenuFitToViewTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick help.
        /// </summary>
        internal static string ContextMenuQuickHelp {
            get {
                return ResourceManager.GetString("ContextMenuQuickHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show brief instructions.
        /// </summary>
        internal static string ContextMenuQuickHelpTooltip {
            get {
                return ResourceManager.GetString("ContextMenuQuickHelpTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report feedback.
        /// </summary>
        internal static string ContextMenuReportFeedback {
            get {
                return ResourceManager.GetString("ContextMenuReportFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an e-mail message to report feedback or submit a bug.
        /// </summary>
        internal static string ContextMenuReportFeedbackTooltip {
            get {
                return ResourceManager.GetString("ContextMenuReportFeedbackTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save screenshot.
        /// </summary>
        internal static string ContextMenuSaveScreenshot {
            get {
                return ResourceManager.GetString("ContextMenuSaveScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify name of image file to save screenshot to.
        /// </summary>
        internal static string ContextMenuSaveScreenshotTooltip {
            get {
                return ResourceManager.GetString("ContextMenuSaveScreenshotTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d3@mslab.cs.msu.su.
        /// </summary>
        internal static string SendFeedbackEmail {
            get {
                return ResourceManager.GetString("SendFeedbackEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seems that there is no a mailto: handler installed.\nJust send an email to.
        /// </summary>
        internal static string SendFeedbackError {
            get {
                return ResourceManager.GetString("SendFeedbackError", resourceCulture);
            }
        }
    }
}
